name: 🐛 Bug Report
description: Report a bug or issue with the GitHub Self-Hosted Runner
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Deploy runner with config '...'
        2. Run workflow '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Runner should execute jobs successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Runner crashes with error message
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please paste relevant logs or error messages
      placeholder: |
        Paste logs here (use docker logs runner-name)
      render: shell
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Deployment (scripts/deploy.sh)
        - Docker Image (Dockerfile)
        - Authentication (GitHub App/JWT)
        - Configuration (runner.env)
        - Cleanup/Maintenance
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: runner-version
    attributes:
      label: Runner Version
      description: Which version of GitHub Actions Runner are you using?
      placeholder: "2.329.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS is the runner deployed on?
      placeholder: "Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: Docker Version
      description: What version of Docker are you using?
      placeholder: "24.0.7"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Share your runner configuration (remove sensitive data!)
      placeholder: |
        REPO_URL=https://github.com/org/repo
        RUNNER_NAME=runner-1
        LABELS=self-hosted,linux,x64,docker
        CPU_LIMIT=2.0
        MEMORY_LIMIT=4g
      render: bash
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included relevant logs and error messages
          required: false
        - label: I have removed sensitive information (tokens, keys, passwords)
          required: true
        - label: I have tested with the latest runner version
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, network setup, special configurations, etc.
    validations:
      required: false
